rootProject.name = 'guspuffy-storm-java-mods'

include('zone-marker')
include('another-vehicle-claim-system')
include('guspuffy-shoutcast-streamer')
include('mouse-vehicle-steering')
include('safe-login')
include('extra-logging')
include('survivor-leaderboard')
include('jumpscare-ban')
include('jumpscare-ban-atf-economy')
include('survivor-loot-respawn')
include('stop-zombie-safehouse-spawns')
include('survivor-skill-obelisk')
include('guspuffy-atf-patches')
include('proximity-inventory')
include('atf-casino')
